ShouldRetrieveTeamByIdAsync -> FAIL
ElbekDeveloper/Tarteeb pull request #117
Opened 2022-12-20 15:52 UTC by jasurbekyusuf

Closes #89

2022-12-20 20:05 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.RetrieveById.cs
> +using System;
order?

2022-12-20 20:08 UTC, jamshidbek001 commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.cs
> +
please remove empty line

2022-12-20 20:08 UTC, jamshidbek001 requested changes
order usings

2022-12-21 07:56 UTC, jamshidbek001 approved these changes
LGTM

2022-12-21 23:25 UTC, ElbekDeveloper approved these changes

2022-12-21 23:26 UTC, merged