FOUNDATIONS: Modify Team
ElbekDeveloper/Tarteeb pull request #122
Opened 2022-12-20 19:45 UTC by jasurbekyusuf

Closes #97

2022-12-21 16:24 UTC, jamshidbek001 commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.Validations.cs
> +            Validate(
need empty line

2022-12-21 16:31 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +            key: nameof(Team.UpdatedDate),
tab

2022-12-21 16:31 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +                    .Returns(randomDateTime);
2 line

2022-12-21 16:32 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +            var invalidTeamException =
1 line

2022-12-21 16:32 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +                .Returns(dateTime);
2 line

2022-12-21 16:33 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +                    Times.Once);
2 line

2022-12-21 16:33 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +                        Times.Once);
3 line

2022-12-21 16:33 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +                    Times.Never);
2 line

2022-12-21 16:34 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +                .ReturnsAsync(storageTeam);
tab

2022-12-21 16:35 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +                .Returns(randomDateTimeOffset);
2 line or need tab

2022-12-21 16:36 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.cs
>          private Expression<Func<Xeption, bool>> SameExceptionAs(Xeption expectedExceptoin) =>
need empty line

2022-12-21 16:37 UTC, jamshidbek001 approved these changes
please check comments

2022-12-21 23:24 UTC, ElbekDeveloper requested changes

2022-12-21 23:24 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.Validations.cs
> +        private static void ValidateAginstStorageTeamOnModify(Team inputTeam, Team storageTeam)
ValidateAginstStorageTeamOnModify =>
`ValidateAgainstStorageTeamOnModify` bo'lishi kk

2022-12-21 23:24 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.cs
> +            ValidateAginstStorageTeamOnModify(inputTeam: team, storageTeam: maybeTeam);
Bu ikkalasi bir metod ichida bo'lishi kk

2022-12-22 14:43 UTC, jamshidbek001 approved these changes

2022-12-22 18:44 UTC, GulchexrasGithub approved these changes
LGTM

2022-12-24 02:54 UTC, Javlonbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.Modify.cs
> +            this.storageBrokerMock.Verify(broker =>
storageBrokerMockni loggingBrokerMockdan keyin qo'ying

2022-12-24 11:13 UTC, StudentofTATU commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.cs
> +            var maybeTeam = await this.storageBroker.SelectTeamByIdAsync(team.Id);
make 2 lines

2022-12-24 11:13 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.Modify.cs
> +                  modifyTeamTask.AsTask);
use TAB

2022-12-24 11:15 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.Modify.cs
> +            SomeTeam.CreatedDate = randomDateTime.AddMinutes(minutesInPast);
change varialbe name to someTeam

2022-12-24 11:16 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.Modify.cs
> +              await Assert.ThrowsAsync<TeamDependencyException>(
use TAB

2022-12-24 11:16 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.Modify.cs
> +                  modifyTeamTask.AsTask);
use TAB

2022-12-24 11:18 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.Modify.cs
> +            this.dateTimeBrokerMock.Verify(broker =>
put this command  above of storageBrokerMock  at 108 line

2022-12-24 11:18 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.Modify.cs
> +            this.dateTimeBrokerMock.VerifyNoOtherCalls();
order

2022-12-24 11:19 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.Modify.cs
> +            Guid TeamId = someTeam.Id;
make variable name teamId

2022-12-24 11:21 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Logic.Modify.cs
> +            Guid TeamId = inputTeam.Id;
make variable name teamId

2022-12-24 11:25 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.Verify(broker =>
this should be before loggingBrokerMock.Verify(..)  at 108 line

2022-12-24 11:28 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +            this.dateTimeBrokerMock.VerifyNoOtherCalls();
order

2022-12-24 11:28 UTC, StudentofTATU requested changes
make some changes

2022-12-24 18:06 UTC, StudentofTATU approved these changes

2022-12-25 11:54 UTC, ElbekDeveloper commented
@jasurbekyusuf conflicts

2022-12-25 11:56 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.Exceptions.cs
> +            catch (DbUpdateException databaseUpdateException)
Buni nega `DbUpdateConcurrencyException` dan keyin qoyilganini bilasiz-a? Bilmasangiz, aytaman `DbUpdateException` dan inheritance oladi. Umumiy xatoliklar pastdan bo'lishi kerak.

2022-12-25 11:59 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Logic.Modify.cs
> +            storageTeam.UpdatedDate = randomTeam.CreatedDate;
Bu shundog'am shu qiymatga egaku? Nima uchun bunday qilingan

2022-12-25 12:00 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.Modify.cs
> +            var invalidTeamException = new InvalidTeamException();
Buni bir tekshirib ko'ring. Xatoga o'xshayapti...

2022-12-29 11:45 UTC, ElbekDeveloper requested changes

2022-12-29 11:45 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.Exceptions.cs
> +            var TeamServiceException = new TeamServiceException(exception);
wrong naming

2022-12-29 11:45 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.Exceptions.cs
> +            var TeamServiceException = new TeamServiceException(exception);
bu service exception dan pastda bo'ladi

2022-12-29 11:45 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.Validations.cs
> +        private static void ValidateStorageTeam(Team maybeTeam, Guid teamId)
bu ValidateStorageTeamExists bo'lsin

2022-12-29 12:42 UTC, ElbekDeveloper approved these changes

2022-12-29 12:42 UTC, merged