FOUNDATIONS: Remove `User`
ElbekDeveloper/Tarteeb pull request #123
Opened 2022-12-21 12:20 UTC by GulchexrasGithub

2022-12-21 17:25 UTC, Javlonbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.RemoveById.cs
> +
Remove Line

2022-12-21 23:27 UTC, ElbekDeveloper requested changes

2022-12-21 23:27 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Users/UserService.cs
> +            User someUser =
someUser emas maybeUser bo'ladi

2022-12-21 23:27 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.RemoveById.cs
> +            await Assert.ThrowsAsync<UserValidationException>(() =>
Bu kerak emas.

2022-12-21 23:27 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.RemoveById.cs
> +                removeUserByIdTask.AsTask());
O'rniga Should().beequ... bo'lishi kerak

2022-12-22 15:30 UTC, jasurbekyusuf commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.RemoveById.cs
> +﻿using System;
Header?

2022-12-22 15:32 UTC, jasurbekyusuf reviewed
LGTM

2022-12-24 02:50 UTC, Javlonbek-dev approved these changes

2022-12-24 10:24 UTC, StudentofTATU commented on Tarteeb.Api/Services/Foundations/Users/UserService.cs
> +               await this.storageBroker.SelectUserByIdAsync(userId);
use TAB

2022-12-24 17:28 UTC, StudentofTATU approved these changes

2022-12-25 11:37 UTC, ElbekDeveloper approved these changes

2022-12-25 11:37 UTC, merged