FOUNDATIONS: Remove Ticket
ElbekDeveloper/Tarteeb pull request #130
Opened 2022-12-22 10:31 UTC by StudentofTATU

Closes #92

2022-12-23 14:10 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.RemoveById.cs
> +                broker.SelectTicketByIdAsync(It.IsAny<Guid>()),
2 line

2022-12-23 14:10 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.RemoveById.cs
> +                    expectedTicketDependencyValidationException))),
3 line

2022-12-23 14:10 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.RemoveById.cs
> +                    Times.Never);
2 line

2022-12-23 14:11 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.RemoveById.cs
> +                        Times.Once);
3 line

2022-12-23 14:12 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.RemoveById.cs
> +                    Times.Never);
2 line

2022-12-23 14:13 UTC, jamshidbek001 requested changes
please correct mistakes

2022-12-24 10:21 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.RemoveById.cs
> +                    Times.Once);
this.loggingBrokerMock.Verify(broker =>
    broker.LogError(It.Is(SameExceptionAs(
        expectedTicketValidationException))),Times.Once);

2022-12-24 10:25 UTC, StudentofTATU commented on Tarteeb.Api/Services/Foundations/Tickets/TicketService.cs
> +                 .SelectTicketByIdAsync(ticketId);
delete extra one space

2022-12-24 10:26 UTC, StudentofTATU reviewed
Check out

2022-12-25 11:53 UTC, merged