FOUNDATIONS: Remove Team
ElbekDeveloper/Tarteeb pull request #135
Opened 2022-12-23 10:18 UTC by jasurbekyusuf

Closes #132

2022-12-23 21:24 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exception.RemoveById.cs
> +            expectedTeamDependencyValidationException))), Times.Once);
Tab

2022-12-23 21:26 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exception.RemoveById.cs
> +            // when
need empty line

2022-12-23 21:34 UTC, jamshidbek001 requested changes
correct the mistakes

2022-12-24 02:43 UTC, Javlonbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Logic.RemoveById.cs
> +                broker.SelectTeamByIdAsync(inputTeamId), Times.Once());
Once() => Once ga o'zgartirasiz

2022-12-24 15:54 UTC, Javlonbek-dev approved these changes

2022-12-24 18:20 UTC, StudentofTATU commented on Tarteeb.Api/Services/Foundations/Teams/ITeamService.cs
> +        ValueTask<Team> RemoveTeamByIdAsync(Guid TeamId);
change variable name teamId

2022-12-24 18:22 UTC, StudentofTATU commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.cs
> +            Team maybeTeam = await this.storageBroker
await this.storageBroker     buni pastdagi qatorga tushiring.

2022-12-24 18:28 UTC, StudentofTATU requested changes
make some changes

2022-12-25 07:23 UTC, StudentofTATU approved these changes

2022-12-25 07:30 UTC, iamDiyorjon reviewed
LGTM

2022-12-25 11:26 UTC, ElbekDeveloper commented on Tarteeb.Api/Controllers/UsersController.cs
> +
Remove this line

2022-12-25 11:28 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.cs
> +            ValidateStorageTeam(maybeTeam, teamId);
Mana shuni `ValidateStorageTeamExists` ga o'zgartiring. Chunki bu metodni qilayotgan ishi shu bo'lyapti

2022-12-25 11:31 UTC, ElbekDeveloper approved these changes

2022-12-25 11:32 UTC, merged