EXPOSERS: Get All Teams
ElbekDeveloper/Tarteeb pull request #136
Opened 2022-12-24 16:43 UTC by GulchexrasGithub

2022-12-24 18:45 UTC, StudentofTATU commented on Tarteeb.Api/Controllers/TeamsController.cs
> +
delete this extra line

2022-12-24 18:45 UTC, StudentofTATU commented on Tarteeb.Api/Controllers/TeamsController.cs
> +
delete this extra line

2022-12-24 18:45 UTC, StudentofTATU requested changes
make some changes

2022-12-26 07:07 UTC, StudentofTATU approved these changes

2022-12-26 11:41 UTC, jamshidbek001 approved these changes

2022-12-26 14:24 UTC, ElbekDeveloper approved these changes

2022-12-26 14:25 UTC, merged