EXPOSERS: Delete Team By Id
ElbekDeveloper/Tarteeb pull request #137
Opened 2022-12-25 15:27 UTC by iamDiyorjon

closes #126

2022-12-26 11:28 UTC, jamshidbek001 commented on Tarteeb.Api/Controllers/TeamsController.cs
> +                return BadRequest(teamValidationException);
innerException?

2022-12-26 11:28 UTC, jamshidbek001 commented on Tarteeb.Api/Controllers/TeamsController.cs
> +                return Locked(teamDependencyValidationException);
innerExveption?

2022-12-26 11:29 UTC, jamshidbek001 commented on Tarteeb.Api/Controllers/TeamsController.cs
> +                return InternalServerError(teamServiceException.InnerException);
needless InnerException

2022-12-26 11:30 UTC, jamshidbek001 requested changes
Check the parametres

2022-12-26 14:03 UTC, jamshidbek001 commented on Tarteeb.Api/Controllers/TeamsController.cs
> +                    await this.teamService.RetrieveTeamByIdAsync(teamId);
RemoveTeamByIdAsync bo'lishi kerak

2022-12-26 14:04 UTC, jamshidbek001 requested changes
Use right Method

2022-12-27 11:59 UTC, StudentofTATU requested changes
Ctrl + k +e

2022-12-29 12:42 UTC, ElbekDeveloper approved these changes

2022-12-29 12:42 UTC, ElbekDeveloper commented on Tarteeb.Api/Controllers/TeamsController.cs
> +            }
Inner Exceptions

2022-12-29 18:26 UTC, ElbekDeveloper approved these changes

2022-12-29 18:26 UTC, merged