EXPOSERS: Delete User
ElbekDeveloper/Tarteeb pull request #138
Opened 2022-12-25 17:22 UTC by jasurbekyusuf

Closes #116

2022-12-26 04:59 UTC, Javlonbek-dev commented on Tarteeb.Api/Controllers/UsersController.cs
> +        [HttpDelete("{userId}")]
Add Line

2022-12-26 11:17 UTC, jamshidbek001 commented on Tarteeb.Api/Controllers/UsersController.cs
> +        public async ValueTask<ActionResult<User>> DeleteUserByIdAsync(Guid usertId)
change parameter to userId

2022-12-26 11:20 UTC, jamshidbek001 requested changes
check parameter

2022-12-26 12:06 UTC, jamshidbek001 approved these changes

2022-12-26 12:10 UTC, Javlonbek-dev approved these changes

2022-12-26 14:16 UTC, ElbekDeveloper requested changes

2022-12-26 14:16 UTC, ElbekDeveloper commented on Tarteeb.Api/Controllers/UsersController.cs
> +                return InternalServerError(userDependencyException);
Nega inner exception qaytarilmayapti?

2022-12-26 14:16 UTC, ElbekDeveloper commented on Tarteeb.Api/Controllers/UsersController.cs
> +                return InternalServerError(userServiceException);
Bunda ham

2022-12-26 14:16 UTC, ElbekDeveloper commented on Tarteeb.Api/Controllers/UsersController.cs
> +                return BadRequest(userDependencyValidationException);
Bunda ham

2022-12-29 11:42 UTC, ElbekDeveloper approved these changes

2022-12-29 11:42 UTC, merged