EXPOSERS: Put Ticket
ElbekDeveloper/Tarteeb pull request #139
Opened 2022-12-25 18:00 UTC by jasurbekyusuf

Closes #121

2022-12-26 11:25 UTC, jamshidbek001 approved these changes

2022-12-27 11:47 UTC, StudentofTATU approved these changes

2022-12-29 11:46 UTC, ElbekDeveloper requested changes

2022-12-29 11:46 UTC, ElbekDeveloper commented on Tarteeb.Api/Controllers/TicketsController.cs
> +                return InternalServerError(ticketServiceException);
InnerException kerak

2022-12-29 12:41 UTC, ElbekDeveloper approved these changes

2022-12-29 12:41 UTC, merged