EXPOSERS: Put Team
ElbekDeveloper/Tarteeb pull request #143
Opened 2022-12-29 13:38 UTC by DadabaevAlisher

2022-12-29 13:44 UTC, sarvarbek-dev reviewed
LGTM

2022-12-29 13:45 UTC, sarvarbek-dev reviewed
LGTM

2022-12-29 13:47 UTC, sarvarbek-dev approved these changes

2022-12-29 13:57 UTC, jasurbekyusuf requested changes

2022-12-29 13:57 UTC, jasurbekyusuf commented on Tarteeb.Api/Controllers/TeamsController.cs
> +            catch (TeamDependencyException teamDependencyException)
InnerException qaytarishi kerak

2022-12-29 14:34 UTC, Javlonbek-dev commented on Tarteeb.Api/Controllers/TeamsController.cs
> +
Remove Line

2022-12-30 15:06 UTC, Javlonbek-dev commented
@DadabaevAlisher  Resolve conflicts

2022-12-30 18:06 UTC, jasurbekyusuf commented on Tarteeb.Api/Controllers/TeamsController.cs
>              }
return InternalServerError(teamServiceException) Change To `return InternalServerError(teamServiceException.InnerException)`

2022-12-30 18:15 UTC, DadabaevAlisher reviewed
CODE RUB: Add InnerException

2022-12-30 18:33 UTC, jasurbekyusuf reviewed
LGTM

2022-12-30 18:33 UTC, jasurbekyusuf approved these changes

2022-12-30 18:33 UTC, merged