EXAMPLE  JWT
ElbekDeveloper/Tarteeb pull request #168
Opened 2023-01-09 14:01 UTC by iamDiyorjon

2023-01-17 09:22 UTC, ElbekDeveloper requested changes

2023-01-21 12:11 UTC, ElbekDeveloper requested changes

2023-01-21 12:11 UTC, ElbekDeveloper commented on Tarteeb.Api/Brokers/Storages/StorageBroker.cs
> +                .IsUnique();
Buni alohida metod qilib. StorageBroker.Users.Configurations.cs ga chiqarib qoying va bu yerda chaqiring

2023-01-21 12:11 UTC, ElbekDeveloper commented on Tarteeb.Api/Brokers/Tokens/JWTOptionsModel.cs
> +        public string SecretKey { get => Environment.GetEnvironmentVariable("SECRET_KEY"); }
Buni appsettingdan olmayapsizlar?

2023-01-21 12:11 UTC, ElbekDeveloper commented on Tarteeb.Api/Brokers/Tokens/TokenBroker.cs
> +        public string GenerateJWT(User user)
@khatanboyevelbek qilyaptilar bu joyini

2023-01-21 12:11 UTC, ElbekDeveloper commented on Tarteeb.Api/Controllers/AccountsController.cs
> +        private readonly IUserOrchestrationService userOrchestrationService;
IUserSecurityOrchestration bo'ladi nomi

2023-01-21 12:11 UTC, ElbekDeveloper commented on Tarteeb.Api/Controllers/AccountsController.cs
> +        public  IActionResult Login(string email, string password)
Biza IActionResult qaytarmaymizku

2023-01-21 12:11 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Processings/UserProcessingService.cs
> +            User validUserOrNot=allUser
return shu yerdan qiling.

2023-01-21 12:14 UTC, 0605AbMu commented on Tarteeb.Api/Brokers/Tokens/JWTOptionsModel.cs
> +        public string SecretKey { get => Environment.GetEnvironmentVariable("SECRET_KEY"); }
Assalomu alaykum.
Ustoz Maqsad ham o'zi shu edi
Ya'ni Secret key ni xavfsiz qilish uchun uni environment o'zgaruvchilardan olmoqchi edik.

2023-01-21 13:05 UTC, 0605AbMu commented on Tarteeb.Api/Brokers/Tokens/JWTOptionsModel.cs
> +        public string SecretKey { get => Environment.GetEnvironmentVariable("SECRET_KEY"); }
Ustoz JWT settings ning data larini bitta classga yig'gan edik. Kerak bo'lgan joyda alohida foydalanib ketaylikmi?

2023-01-23 09:26 UTC, ElbekDeveloper commented
Bu masterga qo'shilmaydigan PR shuning uchun doim DRAFT holda tursin

2023-03-17 16:17 UTC, closed without merging