BROKERS: Create Token Broker And Register It
ElbekDeveloper/Tarteeb pull request #172
Opened 2023-01-17 11:24 UTC by khatanboyevelbek

2023-01-20 11:31 UTC, ElbekDeveloper requested changes

2023-01-20 11:31 UTC, ElbekDeveloper commented on Tarteeb.Api/Brokers/Tokens/TokenBroker.cs
> +                configuration.GetSection("Jwt").GetSection("Audience").Value;
Bu yaxshiroq. Lekin hali aytganimdek emas. 2 ta yo'lingiz bor buni yaxshilash uchun
Birinchisi:

1. `TokenConfiguration` degan model yarating. (Key, Issuer, Audience propertilar bo'lsin)
2. [Bind](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbinder.bind?view=dotnet-plat-ext-7.0#microsoft-extensions-configuration-configurationbinder-bind(microsoft-extensions-configuration-iconfiguration-system-object)) metodi yordamida bittada hammasini qiymatini oling va shu obyektni hamma joyda ishlating. 6 qatorni 1 qatorga tushurasiz shunda


Ikkinchi yo'li: 
1. `IConfigurationSection jwtSection = configuration.GetSection("Jwt");` qilib alohida olib qoyingda 
2. `string secretKey = jwtSection.GetValue<string>(key: "Key"); ` va hokazo qolganlarini ham shunday qiymatini olib chiqing. 
3. GetValue haqida [havola](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbinder.getvalue?view=dotnet-plat-ext-7.0#microsoft-extensions-configuration-configurationbinder-getvalue(microsoft-extensions-configuration-iconfiguration-system-type-system-string))

2023-01-20 11:31 UTC, ElbekDeveloper commented on Tarteeb.Api/Brokers/Tokens/TokenBroker.cs
> +            var secretKey =
o'ng tomon aniq bo'lmaganda chap tomonda tur yoziladi.

2023-01-20 11:32 UTC, ElbekDeveloper commented
Alohida PR ochish kerak emas bu uchun. `CODE RUB: Resolve Comments` commit qilsangiz yetadi

2023-01-20 18:32 UTC, khatanboyevelbek commented on Tarteeb.Api/Brokers/Tokens/TokenBroker.cs
> +            var secretKey =
Kamchiliklarini to'g'rilab qo'ydim ustoz

2023-01-20 18:35 UTC, khatanboyevelbek commented on Tarteeb.Api/Brokers/Tokens/TokenBroker.cs
> +                configuration.GetSection("Jwt").GetSection("Audience").Value;
Ustoz, to'g'rilab qo'ydim kamchiliklarini.

2023-01-21 12:14 UTC, ElbekDeveloper requested changes

2023-01-21 12:14 UTC, ElbekDeveloper commented on Tarteeb.Api/Brokers/Tokens/TokenBroker.cs
> +            tokenConfiguration = new TokenConfiguration();
`tokenConfiguration` private field ligini bildirish uchun `this` ishlatamiz. 

`this.tokenConfiguration`  ga o'zgartirib chiqing

2023-01-21 12:25 UTC, ElbekDeveloper approved these changes

2023-01-21 12:50 UTC, ElbekDeveloper commented on Tarteeb.Api/Models/Tokens/TokenConfiguration.cs
> +        public string? Key { get; set; }
string uchun ? kerak emas

2023-01-21 12:50 UTC, ElbekDeveloper commented on Tarteeb.Api/Models/Tokens/TokenConfiguration.cs
> +
Bu qator ham kerak emas

2023-01-21 13:23 UTC, khatanboyevelbek commented on Tarteeb.Api/Models/Tokens/TokenConfiguration.cs
> +
Aha to'griladim

2023-01-21 14:03 UTC, ElbekDeveloper approved these changes

2023-01-21 14:04 UTC, merged