PROCESSINGS: Retrieve User By Credentials
ElbekDeveloper/Tarteeb pull request #182
Opened 2023-01-28 19:09 UTC by Javlonbek-dev

Closes #154

2023-01-30 05:38 UTC, sarvarbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Processings/Users/UserProcessingsServiceTests.Logic.cs
> +        public void ShouldAddCountryIfNotExistAsync()
why is it written addCountry

2023-01-30 06:45 UTC, Javlonbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Processings/Users/UserProcessingsServiceTests.Logic.cs
> +        public void ShouldAddCountryIfNotExistAsync()
done

2023-02-07 16:04 UTC, sarvarbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Processings/Users/UserProcessingsServiceTests.Logic.cs
> +            string inputpassword = GetrandomString();
use camel case

2023-02-10 11:54 UTC, ElbekDeveloper requested changes

2023-02-10 11:54 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Processings/Users/UserProcessingService.cs
> +            return allUser
Bu metodda hali exception handling va validation yo'q

2023-02-18 16:41 UTC, closed without merging