ShouldCreateToken->PASS
ElbekDeveloper/Tarteeb pull request #184
Opened 2023-02-04 05:53 UTC by iamDiyorjon

2023-02-06 05:43 UTC, Javlonbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/SecurityServiceTests.cs
> +            CreateUserFiller(dates: GetRandomDateTimeOffset()).Create();
Edit the tab

2023-02-06 05:44 UTC, Javlonbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/SecurityServiceTests.cs
> +      new DateTimeRange(earliestDate: DateTime.UnixEpoch).GetValue();
here too

2023-02-10 11:55 UTC, ElbekDeveloper requested changes

2023-02-10 11:55 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/SecurityService.cs
> +        tokenBroker.GenerateJWT(user);
Bunda user validation mavjud emas

2023-02-17 06:30 UTC, ElbekDeveloper requested changes

2023-02-17 06:30 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/SecurityServiceTests.Validations.Create.cs
> +            broker.GenerateJWT(It.IsAny<User>()), Times.Never);
Fix tabs here

2023-02-17 06:30 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/SecurityServiceTests.Validations.Create.cs
> +        public async Task ShouldThrowValidationExceptionOnCreateJWTIfInputIsNullAndLogItAsync()
instead of `async Task` use void

2023-03-17 12:43 UTC, ElbekDeveloper approved these changes

2023-03-17 12:43 UTC, merged