FOUNDATIONS:  Retrieve All `Time`
ElbekDeveloper/Tarteeb pull request #257
Opened 2023-03-28 11:13 UTC by Ulugbek4499

Closes #224

2023-03-28 11:32 UTC, ShohruhUzDev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.Logic.RetrieveAll.cs
> +﻿using System;
add header file

2023-03-28 11:34 UTC, ShohruhUzDev commented on Tarteeb.Api/Services/Foundations/Times/TimeService.cs
> +        IStorageBroker storageBroker;
add "private readonly"

2023-03-28 11:38 UTC, ShohruhUzDev commented
Menimcha Testni Exceptions qismini ham yozishiz kerak

2023-03-29 08:55 UTC, Javlonbek-dev requested changes

2023-03-29 08:55 UTC, Javlonbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.Logic.RetrieveAll.cs
> +                broker.SelectAllTimes()).Returns(storageTimes);
add empty line

2023-03-29 11:51 UTC, closed without merging