FOUNDATIONS: Delete `Time`
ElbekDeveloper/Tarteeb pull request #259
Opened 2023-03-29 15:29 UTC by AbbosHaydarov

Closes #226

2023-03-30 13:49 UTC, khabibulladev requested changes

2023-03-30 13:49 UTC, khabibulladev commented on Tarteeb.Api/Models/Foundations/Times/Exceptions/TimeValidationException.cs
> +            : base(message: "Time validation error occured, fix the errors and try again.", innerException)
occured -> occured

2023-03-30 13:49 UTC, khabibulladev commented on Tarteeb.Api/Services/Foundations/Times/TimeService.cs
> +            TryCatch(async () =>
Remove a tab

2023-03-31 11:30 UTC, ElbekDeveloper commented
startupda registratsiya qilinmagan

2023-03-31 13:06 UTC, AbbosHaydarov commented on Tarteeb.Api/Models/Foundations/Times/Exceptions/TimeValidationException.cs
> +            : base(message: "Time validation error occured, fix the errors and try again.", innerException)
hazillashdizooov aa Aylis 9+

2023-03-31 16:25 UTC, GulchexrasGithub commented on Tarteeb.Api/Models/Foundations/Teams/Exceptions/NotFoundTeamException.cs
> +            : base(message: $"Couldn't find time with id: {teamId}.")
O'zi to'g'ri edi, time ni teamga o'zgartiring.

2023-03-31 16:30 UTC, GulchexrasGithub commented on Tarteeb.Api/Services/Foundations/Times/TimeService.Validations.cs
> +            Validate((IsInvalid(timeId), nameof(Time.Id)));
`Validate((Rule: IsInvalid(timeId), Parametr: nameof(Time.Id)));

2023-03-31 16:41 UTC, GulchexrasGithub commented on Tarteeb.Api/Services/Foundations/Times/TimeService.Exceptions.cs
> +                throw CreateAndDependencyValidationException(lockedTimeException);
`CreateAndDependencyValidationException` => `CreateAndLogDependencyValidationException`

2023-03-31 16:44 UTC, GulchexrasGithub commented on Tarteeb.Api/Services/Foundations/Times/TimeService.Exceptions.cs
> +            Exception exception)
Exception emas Xeption

2023-03-31 17:05 UTC, GulchexrasGithub commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.Validations.RemoveById.cs
> +
`this.storageBrokerMock.Verify(broker =>
				broker.DeleteTimeAsync(It.IsAny<Time>()),
					Times.Never);`

2023-03-31 17:13 UTC, GulchexrasGithub commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.Exceptions.RemoveById.cs
> +            var sqlException = CreateSqlException();
SqlException sqlException

2023-03-31 17:17 UTC, GulchexrasGithub commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.Exceptions.RemoveById.cs
> +                broker.SelectTimeByIdAsync(someTimeId), Times.Once);
`broker.SelectTimeByIdAsync(someTimeId), Times.Once);` => `broker.SelectTimeByIdAsync(It.IsAny<Guid>()), Times.Once);`

2023-03-31 17:23 UTC, GulchexrasGithub requested changes
TimeServiceTests classidagi hamma funksyalar static bo'lishi kerak.

2023-03-31 17:36 UTC, AbbosHaydarov commented
> TimeServiceTests classidagi hamma funksyalar static bo'lishi kerak.

Resolved All of Comments

2023-03-31 18:43 UTC, GulchexrasGithub commented on Tarteeb.Api/Services/Foundations/Times/TimeService.Exceptions.cs
> +        private TimeDependencyValidationException CreateAndDependencyValidationException(Xeption exception)
`CreateAndDependencyValidationException` => `CreateAndLogDependencyValidationException`

2023-04-01 06:41 UTC, Nodirkhan commented on Tarteeb.Api/Services/Foundations/Times/TimeService.Exceptions.cs
> +        private TimeDependencyValidationException CreateAndDependencyValidationException(Xeption exception)
Done

2023-04-01 07:21 UTC, GulchexrasGithub approved these changes

2023-04-01 07:34 UTC, GulchexrasGithub commented
Again conflicts

2023-04-01 08:23 UTC, jasurbekyusuf reviewed
LGTM

2023-04-01 08:24 UTC, ElbekDeveloper commented on Tarteeb.Api/Models/Foundations/Times/Exceptions/NotFoundTimeException.cs
> +            : base(message: $"Couldn't find team with id: {timeId}.")
team ? => time bo'ladi

2023-04-01 08:26 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Foundations/Times/TimeService.Exceptions.cs
> +            catch (Exception serviceException)
Birinchi SQL exception handle qilinadi. Keyinhchalik dbupdate exception. Bu yerda va testda ham to'g'rilang

2023-04-01 08:55 UTC, ElbekDeveloper approved these changes

2023-04-01 08:55 UTC, merged