BROKERS: Send Email Confirmation And Register It
ElbekDeveloper/Tarteeb pull request #260
Opened 2023-03-29 17:23 UTC by khatanboyevelbek

Closes #220

2023-03-29 17:36 UTC, AbbosHaydarov commented on Tarteeb.Api/Brokers/Emails/EmailConfirmationBroker.cs
> +            return result;
result bilan return orasida bitta line qolishi kerak

2023-03-29 17:36 UTC, AbbosHaydarov commented on Tarteeb.Api/Brokers/Emails/EmailConfirmationBroker.cs
> +        {
bu yerda codimiz bir qator bolganligi uchun lambda expressiondan foydalansak boladimi

2023-03-29 17:36 UTC, AbbosHaydarov commented on Tarteeb.Api/Brokers/Emails/EmailConfirmationBroker.cs
> +﻿using System.Threading.Tasks;
Add header file

2023-03-29 17:36 UTC, AbbosHaydarov commented on Tarteeb.Api/Startup.cs
>  using Microsoft.IdentityModel.Tokens;
bu yerda ham

2023-03-30 07:16 UTC, AbbosHaydarov commented on Tarteeb.Api/Brokers/Emails/EmailConfirmationBroker.cs
> +
buyerda bitta line ortiqcha.

2023-03-31 11:29 UTC, ElbekDeveloper requested changes

2023-03-31 11:29 UTC, ElbekDeveloper commented on Tarteeb.Api/Brokers/Emails/EmailConfirmationBroker.cs
> +                this.Configuration.GetSection("Postmark").GetValue<string>("ApiKey");
buni soddalashtiring

2023-04-01 07:56 UTC, ElbekDeveloper commented
![image](https://user-images.githubusercontent.com/52498074/229273507-16d75a1e-a53b-46a7-8045-29cae859ca0f.png)
Hech qanday email yuborilmagan deyapti. Buni test qilib ko'rmadingizmi?

2023-04-02 05:07 UTC, merged