FOUNDATIONS:  `Time` Retrieve All
ElbekDeveloper/Tarteeb pull request #262
Opened 2023-03-31 15:57 UTC by Ulugbek4499

Closes #257

2023-03-31 19:50 UTC, GulchexrasGithub commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.Logic.RetrieveAll.cs
> +            //when
Empty line required

2023-03-31 19:54 UTC, GulchexrasGithub commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.cs
> +        private static string GetRandomString() =>
Empty line required

2023-03-31 20:01 UTC, GulchexrasGithub requested changes
Retrieve All Timega oid bo'lmagan classlarni tozalamang.

2023-04-01 06:08 UTC, Ulugbek4499 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.Logic.RetrieveAll.cs
> +            //when
Resolved

2023-04-01 06:16 UTC, Ulugbek4499 commented on Tarteeb.Api/Services/Foundations/Times/TimeService.Exceptions.cs
> +        private TimeServiceException CreateAndLogServiceException(Exception exception)
Resolved

2023-04-01 06:19 UTC, Ulugbek4499 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/TimeSlots/TimeServiceTests.cs
> +        private static string GetRandomString() =>
resolved

2023-04-01 06:26 UTC, Ulugbek4499 commented
> Retrieve All Timega oid bo'lmagan classlarni tozalamang.

Please give more info about it.

2023-04-01 07:16 UTC, GulchexrasGithub commented
> > Retrieve All Timega oid bo'lmagan classlarni tozalamang.
> 
> Please give more info about it.

Don't clean files you did'nt work on, for example you have cleaned 

> > Retrieve All Timega oid bo'lmagan classlarni tozalamang.
> 
> Please give more info about it.

Don't clean files you did'nt work on, for example you have cleaned 
`Tarteeb.Api/Services/Orchestrations/UserSecurityOrchestrationService.Exceptions.cs`
`Tarteeb.Api/Models/Orchestrations/UserTokens/Exceptions/FailedUserTokenOrchestrationException.cs`
`Tarteeb.Api/Controllers/TicketsController.cs`
`Tarteeb.Api/Brokers/Storages/StorageBroker.Users.cs`
`Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.cs` and others, but you didn't work on this files.  Use `Ctrl k e` for clean.

2023-04-01 07:18 UTC, GulchexrasGithub approved these changes

2023-04-01 07:28 UTC, Ulugbek4499 commented
> > > Retrieve All Timega oid bo'lmagan classlarni tozalamang.
> > 
> > 
> > Please give more info about it.
> 
> Don't clean files you did'nt work on, for example you have cleaned
> 
> > > Retrieve All Timega oid bo'lmagan classlarni tozalamang.
> > 
> > 
> > Please give more info about it.
> 
> Don't clean files you did'nt work on, for example you have cleaned `Tarteeb.Api/Services/Orchestrations/UserSecurityOrchestrationService.Exceptions.cs` `Tarteeb.Api/Models/Orchestrations/UserTokens/Exceptions/FailedUserTokenOrchestrationException.cs` `Tarteeb.Api/Controllers/TicketsController.cs` `Tarteeb.Api/Brokers/Storages/StorageBroker.Users.cs` `Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.cs` and others, but you didn't work on this files. Use `Ctrl k e` for clean.

Thanks, I got it!

2023-04-01 07:31 UTC, merged