DATA: Model & Migrate `Milestone`
ElbekDeveloper/Tarteeb pull request #323
Opened 2023-04-16 13:29 UTC by Jahongir1507

closes #309

2023-04-16 15:26 UTC, ShohruhUzDev approved these changes

2023-04-16 18:23 UTC, ElbekDeveloper requested changes

2023-04-16 18:23 UTC, ElbekDeveloper commented on Tarteeb.Api/Models/Foundations/Milestones/Milestone.cs
> +    }
``` csharp
public class Milestone
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Discription { get; set; }
        public DateTimeOffset Deadline { get; set; }

        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        
         public Guid AssigneeId { get; set; }
         public User Assignee { get; set; }  
    }

````

Bunday bo'lishi kerak. Chunki biz User classini Milestone bilan AssigneeId yordamida ulaypmiz.

2023-04-17 03:29 UTC, ElbekDeveloper approved these changes

2023-04-17 03:30 UTC, merged