FOUNDATIONS : Hash Password
ElbekDeveloper/Tarteeb pull request #374
Opened 2023-05-01 09:51 UTC by ShohruhUzDev

Closes #363

2023-05-01 10:33 UTC, ElbekDeveloper requested changes

2023-05-01 10:33 UTC, ElbekDeveloper commented on Tarteeb.Api/Brokers/Tokens/TokenBroker.cs
> +        }
You cannot implement broker in foundation service:
 public string HashToken(string password) =>
    throw new NotImplementedException();

ga o'zgartirib. Buning uchun alohida brokers PR oching

2023-05-01 10:33 UTC, ElbekDeveloper commented on Tarteeb.Api/Services/Orchestrations/UserSecurityOrchestrationService.cs
> +            user.Password=this.securityService.HashPassword(user.Password);
format around `=` sign

2023-05-01 10:33 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Tarteeb.Api.Tests.Unit.csproj
> +		<PackageReference Include="PasswordGenerator" Version="2.1.0" />
Bu qanaqa kutubxona ekan. Bizga bu kerak emas.

2023-05-01 10:33 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Tarteeb.Api.Tests.Unit.csproj
> +		<PackageReference Include="PasswordGenerator" Version="2.1.0" />
Oddiy string bilan tuzib chiqing. Object filler bunga imkon berishi mumkin.

2023-05-01 10:33 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.Validations.Hash.cs
> +                values: "Password is not valid");
Bu yerda parolda nima muammoligi ko'rinmayaptiku

2023-05-01 11:18 UTC, ShohruhUzDev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.Validations.Hash.cs
> +                values: "Password is not valid");
Invalid Password kelayapdiku

2023-05-07 15:56 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.Validations.Hash.cs
> +            invalidPasswordException.AddData(
bu kerakmas

2023-05-07 16:58 UTC, closed without merging