FOUNDATIONS: Modify Ticket
ElbekDeveloper/Tarteeb pull request #84
Opened 2022-12-03 23:04 UTC by XusanDeveloper

2022-12-20 09:35 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +            NullTicketException nullTicketException = new NullTicketException();
var

2022-12-20 10:10 UTC, Javlonbek-dev commented on Tarteeb.Api/Services/Foundations/Tickets/TicketService.cs
> +
Remove Line

2022-12-20 15:09 UTC, jamshidbek001 commented on Tarteeb.Api/Services/Foundations/Tickets/TicketService.cs
>  using System;
order

2022-12-20 15:15 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +            ValueTask<Ticket> addTicketTask = this.ticketService.ModifyTicketAsync(invalidTicket);
modifyTicketTask

2022-12-20 15:17 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +                    Times.Once);
2 line

2022-12-20 15:17 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +                       Times.Once);
3 line

2022-12-20 15:19 UTC, jamshidbek001 requested changes
please order using

2022-12-20 18:27 UTC, XusanDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +                       Times.Once);
Done

2022-12-20 18:27 UTC, XusanDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +                    Times.Once);
Done

2022-12-20 18:31 UTC, XusanDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +            ValueTask<Ticket> addTicketTask = this.ticketService.ModifyTicketAsync(invalidTicket);
Done

2022-12-21 23:28 UTC, ElbekDeveloper commented
Conflicts

2022-12-22 14:28 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +        public async Task ShouldThrowValidationExceptionOnModifyIfUpdatedDateIsSameAsCreatedDateAndLogItAsync()
UpdatedDateIsNotSameAs bo'lsa kerak

2022-12-22 14:28 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.Modify.cs
> +
dateTimeBroker?

2022-12-22 14:35 UTC, jamshidbek001 reviewed
Add dateTimeBroker

2022-12-23 13:45 UTC, jamshidbek001 approved these changes

2022-12-23 13:45 UTC, merged