FOUNDATIONS: Retreive All Teams
ElbekDeveloper/Tarteeb pull request #96
Opened 2022-12-10 08:59 UTC by GulchexrasGithub

Closes #87

2022-12-11 07:00 UTC, Javlonbek-dev commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.Exceptions.cs
> +        private delegate IQueryable<Team> ReturningTeamsFunction();
Add Line

2022-12-11 16:13 UTC, jamshidbek001 commented on Tarteeb.Api/Models/Users/Exceptions/UserServiceException.cs
> +        : base(message: "User service error occurred, contact support.", innerException)
Need Tab

2022-12-11 16:17 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.cs
> +                DateTime.UnixEpoch).GetValue();
2 line

2022-12-11 16:28 UTC, jamshidbek001 commented on Tarteeb.Api/Services/Foundations/Teams/TeamService.Exceptions.cs
> +        private IQueryable<Team> TryCatch(ReturningTeamsFunction returningTeamsFunction)
Need empty line

2022-12-13 05:30 UTC, jasurbekyusuf approved these changes

2022-12-13 07:31 UTC, Javlonbek-dev commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.RetrieveAll.cs
> +
Remove Line

2022-12-15 15:42 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.RetrieveAll.cs
> +            this.storageBrokerMock.Verify(broker => broker.SelectAllTeams());
Times.Once qolib ketibti

2022-12-15 15:42 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.RetrieveAll.cs
> +            this.dateTimeBrokerMock.VerifyNoOtherCalls();
Bu pastda bo'ladi

2022-12-15 15:43 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.RetrieveAll.cs
> +            Assert.Throws<TeamDependencyException>(retrieveAllTeamsAction);
Bu eski standard. Yangisiga ko'chiring

2022-12-15 15:43 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.RetrieveAll.cs
> +            this.dateTimeBrokerMock.VerifyNoOtherCalls();
Fix order here

2022-12-15 15:43 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Logic.RetrieveAll.cs
> +            IQueryable<Team> expectedTeam = storageTeams;
expectedTeams

2022-12-15 15:44 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Logic.RetrieveAll.cs
> +            IQueryable<Team> actualTeam = this.teamService.RetrieveAllTeams();
actualTeams

2022-12-15 15:44 UTC, ElbekDeveloper commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.cs
> +using System;
Order these

2022-12-20 06:02 UTC, StudentofTATU requested changes

2022-12-20 06:02 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.cs
> +            filler.Setup().OnType<DateTimeOffset>().Use(GetRandomDateTimeOffset());
.Use(GetRandomDateTimeOffset()); put this code to next line or remove above Empty line

2022-12-21 09:50 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.RetrieveAll.cs
> +            Assert.Throws<TeamDependencyException>(retrieveAllTeamsAction);
Use      Should().BeEquivalentTo

https://github.com/ElbekDeveloper/Tarteeb/blob/master/Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.RetrieveAll.cs

2022-12-21 09:51 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.RetrieveAll.cs
>                     .Throws(sqlException);
TAB

2022-12-21 09:54 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.RetrieveAll.cs
22-line expectedUser  change to expectedUsers

2022-12-21 09:55 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.RetrieveAll.cs
22-line expectedUser  change to expectedUsers

2022-12-22 17:39 UTC, StudentofTATU commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.RetrieveAll.cs
>                     .Throws(sqlException);
TAB

2022-12-24 10:06 UTC, StudentofTATU approved these changes

2022-12-24 12:06 UTC, merged