FOUNDATIONS: Modify User
ElbekDeveloper/Tarteeb pull request #99
Opened 2022-12-11 04:50 UTC by iamDiyorjon

2022-12-22 15:48 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
> +using Microsoft.EntityFrameworkCore;
order

2022-12-22 15:50 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
> +                   .Throws(sqlException);
2 line and before broker need tab

2022-12-22 15:50 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
> +            await Assert.ThrowsAsync<UserDependencyException>(() =>
upgrade new standard

2022-12-22 15:55 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
> +                    .Returns(randomDateTime);
2 line

2022-12-23 13:49 UTC, jamshidbek001 commented on Tarteeb.Api/Services/Foundations/Users/UserService.Validations.cs
> +        private void ValidationUserOnModify(User user)
ValidateUserOnModify bo'lishi kerak

2022-12-23 13:50 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
> +               broker.GetCurrentDateTime()).Throws(sqlException);
Tab

2022-12-23 13:51 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
> +               broker.SelectUserByIdAsync(randomUser.Id), Times.Never);
tab

2022-12-23 13:51 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
> +                   Times.Never);
2 line

2022-12-23 13:52 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Modify.cs
> +              await Assert.ThrowsAsync<UserDependencyException>(modifyUserTask.AsTask);
tab

2022-12-23 13:56 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.Add.cs
> +            DateTimeOffset randomDateTime = GetRandomDateTimeOffset();
It should be GetRandomDateTime without Offset

2022-12-23 13:58 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.Modify.cs
> +                broker.SelectUserByIdAsync(userId),
2 line

2022-12-23 13:58 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.Modify.cs
> +                broker.UpdateUserAsync(inputUser),
2 line

2022-12-23 13:59 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validation.Modify.cs
> +            var invalidUserException =
1 line

2022-12-23 13:59 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validation.Modify.cs
> +               broker.GetCurrentDateTime()).Returns(randomDatetime);
tab

2022-12-23 14:00 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validation.Modify.cs
> +            var invalidUserException =
1 line

2022-12-23 14:02 UTC, jamshidbek001 commented on Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.cs
> +            return new TheoryData<int>
need empty line

2022-12-23 14:03 UTC, jamshidbek001 requested changes
please correct tabs

2022-12-24 18:38 UTC, StudentofTATU approved these changes
LGTM

2022-12-25 14:29 UTC, jamshidbek001 approved these changes

2022-12-26 08:42 UTC, merged